---
resources:

- name: git_push 
  type: git
  source:
    uri: git@github.com:niharbabu99/testingconcourse.git
    private_key: ((p_key))
    branch: master

jobs:
- name: gitpush-test
  serial: true
  plan:
  - get: git_push
  - task: check
    file: git_push/script/configure.yml
  - put: git_push
    params:
      repository: git_push_modified
      rebase: true
