---
   
platform: linux
image_resource:
  type: docker-image
  source: {repository: ndevathi/ubuntu_bosh}
inputs:
- name: git_push
outputs:
- name: ((oupu))
run:
  path: git_push/script/configure.sh

